name: Fetch Brent 5-min data

on:
  # автоматически каждые 30 минут
  schedule:
    - cron: "*/30 * * * *"
  # возможность запустить вручную из вкладки Actions
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

- name: Download Brent CSV (retry until not empty)
  run: |
    set -e
    url="https://stooq.com/q/d/l/?s=cb.f&i=5"
    for n in {1..5}; do
      curl -fLs -H "User-Agent: GitHubActions" \
        -H "Referer: https://stooq.com" \
        "$url" -o /tmp/brent.csv

      # если файл > 10 KB — считаем его валидным
      if [ $(stat -c%s /tmp/brent.csv) -gt 10240 ]; then
        echo "CSV looks OK (size >10 KB)"
        break
      fi
      echo "Empty CSV (try $n/5) — retry in 30 s"
      sleep 30
    done

    if [ $(stat -c%s /tmp/brent.csv) -le 10240 ]; then
      echo "::error::Stooq returned empty CSV after 5 tries"
      exit 1
    fi

    # обёртка в HTML
    {
      echo '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>'
      echo '<pre id="data">'
      cat /tmp/brent.csv
      echo '</pre></body></html>'
    } > brent_5min.html
