name: Fetch Brent 5-min data
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Brent CSV (5-min)
        run: |
          curl -Ls -H "User-Agent: GitHubActions" \
            "https://stooq.com/q/d/l/?s=cb.f&i=5" \
            -o brent_5min.csv
      - name: Commit & push
        env:
          TZ: UTC
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add brent_5min.csv
          git commit -m "Auto-update Brent 5-min $(date -u '+%Y-%m-%d %H:%M UTC')" || echo "No changes"
          git push
