name: Fetch Brent 5-min data
on:
  schedule:
    - cron: "*/30 * * * *"     # каждые 30 минут
  workflow_dispatch:           # запуск вручную

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Brent CSV & wrap to HTML
        run: |
          set -e
          curl -Ls -H "User-Agent: GitHubActions" \
               -H "Referer: https://stooq.com" \
               "https://stooq.com/q/d/l/?s=cb.f&i=5" \
               -o /tmp/brent.csv

          # Обёртка в минимальный HTML
          {
            echo '<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>'
            echo '<pre id="data">'
            cat /tmp/brent.csv
            echo '</pre></body></html>'
          } > brent_5min.html

      - name: Commit & push
        env:
          TZ: UTC
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add brent_5min.html
          git commit -m "Auto-update Brent 5-min $(date -u '+%Y-%m-%d %H:%M UTC')" || echo "No changes"
          git push
